on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        TOKEN: ${{ secrets.TOKEN }}